// lab4/src/App.tsx
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.scss';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';
import About from './components/About/About';
import Features from './components/Features/Features';
import Tours from './components/Tours/Tours';
import Stories from './components/Stories/Stories';

class App extends Component {
  render() {
    return(<React.Fragment>
            <Header/>
            <About/>
            <Features/>
            <Tours/>
            <Stories/>
            <Footer/>
          </React.Fragment>);
  }
}

export default App;

// Lab5/src/App.vue
<template>
  <div>
    <Header/>
    <About/>
    <Features/>
    <Tours/>
    <Stories/>
    <Footer/>
  </div>
  <!-- <router-view> -->
</template>

<script>
import Header from '@/components/header/Header.vue';
import Footer from '@/components/footer/Footer.vue';
import About from '@/components/about/About.vue';
import Features from '@/components/features/Features.vue';
import Tours from '@/components/tours/Tours.vue';
import Stories from '@/components/stories/Stories.vue';
import Vue from 'vue';
import Component from 'vue-class-component'
import Fragment from 'vue-fragment'
Vue.use(Fragment.Plugin)

// export default class App extends Vue ({
//   name: 'App',
//   components: {
//     Header,
//     Footer,
//     About,
//     Features
//   }
// })
@Component({
  components: {
    Header, 
    About, 
    Features,
    Tours,
    Stories,
    Footer
  }
})
export default class App extends Vue {
  
}
</script>
